# modify header dict to change names of each col
# modify default_cols list to modify columns shown by default
#   - entries should be a key from the headers dict
#   - columns are shown in same order they appear (except for year / link / thread, which have a predefined position for formatting reasons)

# ____ Cog settings ____

equip_headers:
  date: "# Auction / MM-YY"
  price: Price
  level: Level
  stats: Percentiles
  seller: Seller
  buyer: Buyer
  link: ""
  forum: ""
  name: Equip Name

summary_headers:
    #col headers
    equip_category: ""
    total_count: Count
    total_credits: Credits

    # row headers
    total: ">Total<"

# ____ Command settings ____

auction:
  default_cols: [price, level, stats, date]
  stat_col_width: 40
  page_limit_server: 2
  page_limit_dm: 999

bought:
  default_cols: [name, price, level, stats, date]
  stat_col_width: 40
  page_limit_server: 2
  page_limit_dm: 999

  # keys are row names for user summary
  # equips containing at least one value in list will be added to that category
  groups:
    1H: [axe, club, rapier, shortsword, wakizashi]
    2H: [estoc, longsword, mace, katana]
    Staff: [oak, redwood, willow, katalox]
    Shield: [buckler, kite, force]
    Cloth: [cotton, phase]
    Light: [leather, leather]
    Heavy: [plate, power]

sold:
  default_cols: [name, price, level, stats, date]
  stat_col_width: 20
  page_limit_server: 2
  page_limit_dm: 999

  # keys are row names for user summary
  # equips containing at least one value in list will be added to that category
  groups:
    1H: [axe, club, rapier, shortsword, wakizashi]
    2H: [estoc, longsword, mace, katana]
    Staff: [oak, redwood, willow, katalox]
    Shield: [buckler, kite, force]
    Cloth: [cotton, phase]
    Light: [leather, leather]
    Heavy: [plate, power]



# ____ Do-not-modify section ____

# keywords in query --> keys in data dict
key_map:
  min: price
  max: price
  date: date
  name: name
  seller: seller
  buyer: buyer
  link: link
  thread: thread