max_body_length: 250
max_body_lines: 6
max_title_length: 50
max_tries: 3 # for pages that require login (namely bounties)
hath_value: 3700

thread_title_template: |-
  {{TITLE}}

thread_body_template: |-
  {{SUB_TITLE}}
  ```fix
  {{BODY}}
  ```
  by [{{USERNAME}}]({{USER_LINK}}) | {{"%02d"|format(YEAR)}}-{{"%02d"|format(MONTH)}}-{{"%02d"|format(DAY)}}

comment_title_template: |-
  {{TITLE}}

comment_body_template: |-
  ```fix
  {{BODY}}
  ```
  by [{{USERNAME}}]({{USER_LINK}}) | {{"%02d"|format(YEAR)}}-{{"%02d"|format(MONTH)}}-{{"%02d"|format(DAY)}}

bounty_title_template: |-
  {{TITLE}}

bounty_body_template: |-
  ```css
  [ {{TYPE}} | ~{{CREDIT_VALUE}} Credits | {{STATUS}} ]

  {{BODY}}
  ```
  by [{{USERNAME}}]({{USER_LINK}}) | {{"%02d"|format(YEAR)}}-{{"%02d"|format(MONTH)}}-{{"%02d"|format(DAY)}}