help_string: "Exception lists are checked in the order of command --> cog --> server\
  \ (smallest to largest).\nWithin each level / list, the topmost, the first matching\
  \ exception is used to determine if the command succeeds / fails.\n\nFor example,\
  \ with the listing below, only the user with id 122 and holding roles with ids 344\
  \ / 566\nmay post in the channel with id 788.\n\n# Command-level\nhelp:\n  everyone:\
  \ *pass\n  exceptions:\n  amy: { value: *allow, user: 122, roles: [344, 566] }\n\
  \  channel_ban: { value: *allow, channel: 788 }\n\nNote that \"amy\" / \"channel_ban\"\
  \ here can be any memorable identifiers.\nAlso note that values for \"user\" and\
  \ \"channel\" must be ints whereas the value for \"roles\" must be a list of int.\n\
  \nWhen multiple criteria / ids are used, ALL criteria / ids must be met for the\
  \ exception to apply.\n\nIf the \"everyone\" key for a level is set to...\n*allow\
  \ - the command will be allowed if no exceptions in the current level are matched\n\
  *fail - the command will fail if no exceptions in the current level are matched\n\
  *pass - the next level of exceptions will be checked. If there is no next level,\
  \ the command will fail.\n(Remember that exceptions are checked in the order of\
  \ command-level -> cog-level -> server-level!!)\n\nIf \"vocal_fail\" mode is enabled,\
  \ a failed-permissions message will be sent to the user. If \"details\" is also\
  \ enabled,\nthe reason (eg exception entry) will also be printed."
flags:
  ALLOW: 1
  PASS: 0
  FAIL: -1
vocal_fail: false
details: false
everyone: -1
exceptions:
- value: 1
  channel: 563523595322785833
none:
  everyone: 0
  exceptions: []
  help:
    everyone: 0
    exceptions: []
Auction:
  everyone: 0
  exceptions: []
  auction:
    everyone: 0
    exceptions: []
Item:
  everyone: 0
  exceptions: []
  item:
    everyone: 0
    exceptions: []
Equip:
  everyone: 0
  exceptions: []
  equip:
    everyone: 0
    exceptions: []
  auction:
    everyone: 0
    exceptions: []
  bought:
    everyone: 0
    exceptions: []
Preview:
  everyone: 1
  exceptions: []
  preview:
    everyone: 0
    exceptions: []
Reaction:
  everyone: 0
  exceptions: []
  addrr:
    everyone: 0
    exceptions: []
  reaction_delete:
    everyone: 0
    exceptions: []
  reaction_role:
    everyone: 0
    exceptions: []
  listroles:
    everyone: 0
    exceptions: []
  getrr:
    everyone: 0
    exceptions: []
  editrr:
    everyone: 0
    exceptions: []
