# REQUIRES BOT RESTART TO APPLY
#
# Settings for cog display name and command alisases

auction:
  cog_name: Auction
  commands:

    auction:
      name: auction
      short: auc

    bought: # deprecated -- will remove later
      name: bought
      short: bou

    sold: # deprecated -- will remove later
      name: sold
      short: sol

item:
  cog_name: Item
  commands:

    item:
      name: item
      short: it